---
- name: Install Apache Tomcat 10 using Ansible
  hosts: webservers
  remote_user: ec2-user
  become: true
  vars:
    tomcat_version: "10.0.4"
    tomcat_download_url: "https://dlcdn.apache.org/tomcat/jakartaee-migration/v1.0.7/binaries/jakartaee-migration-1.0.7-bin.tar.gz"
    tomcat_install_directory: "/opt/tomcat10"

  tasks:
    - name: Update the System Packages
      yum:
        name: "*"
        state: latest
        update_cache: yes

    - name: Create a Tomcat User
      user:
        name: tomcat
        system: yes
        createhome: false

    - name: Create a Tomcat Group
      group:
        name: tomcat
        system: yes

    - name: Install Java
      yum:
        name: java-11-openjdk
        state: present

    - name: Create a Tomcat Directory
      file:
        path: "{{ tomcat_install_directory }}"
        owner: tomcat
        group: tomcat
        mode: 0755
        state: directory

    - name: Download & Unarchive Tomcat 10
      unarchive:
        src: "{{ tomcat_download_url }}"
        dest: "{{ tomcat_install_directory }}"
        remote_src: yes
        extra_opts: [--strip-components=1]
        owner: tomcat
        group: tomcat

    - name: Set Correct Permissions for Tomcat Directory
      file:
        path: "{{ item }}"
        owner: tomcat
        group: tomcat
        mode: u+rwx,g+rx,o=rx
        recurse: yes
      with_items:
        - "{{ tomcat_install_directory }}"
        - "{{ tomcat_install_directory }}/conf"
        - "{{ tomcat_install_directory }}/webapps"
        - "{{ tomcat_install_directory }}/logs"
        - "{{ tomcat_install_directory }}/temp"
        - "{{ tomcat_install_directory }}/bin"

    - name: Copy Tomcat Service from local to remote
      copy:
        src: /etc/tomcat.service  # Ensure this file is correctly configured and present in your Ansible project directory
        dest: /etc/systemd/system/tomcat.service
        mode: 0755
      notify: reload systemd

    - name: Start and Enable Tomcat 10 on server
      systemd:
        name: tomcat
        enabled: yes
        state: started

  handlers:
    - name: reload systemd
      systemd:
        daemon_reload: yes
