---
- name: Install Apache Tomcat 10 using Ansible
  hosts: webservers
  remote_user: ec2-user
  become: true
  vars:
    tomcat_download_url: "https://dlcdn.apache.org/tomcat/jakartaee-migration/v1.0.7/binaries/jakartaee-migration-1.0.7-bin.tar.gz"
    tomcat_install_directory: "/opt/tomcat10"

  tasks:
    - name: Update the System Packages
      yum:
        name: "*"
        state: latest
        update_cache: yes

    - name: Create a Tomcat User
      user:
        name: tomcat
        system: yes
        createhome: false

    - name: Create a Tomcat Group
      group:
        name: tomcat
        system: yes

    - name: Install Java
      yum:
        name: java-11-openjdk
        state: present

    - name: Create a Tomcat Directory
      file:
        path: "{{ tomcat_install_directory }}"
        owner: tomcat
        group: tomcat
        mode: 0755
        state: directory

    - name: Download & Unarchive Tomcat 10
      unarchive:
        src: "{{ tomcat_download_url }}"
        dest: "{{ tomcat_install_directory }}"
        remote_src: yes
        extra_opts: [--strip-components=1]
        owner: tomcat
        group: tomcat

    - name: Set Correct Permissions for Tomcat Directory
      file:
        path: "{{ item }}"
        owner: tomcat
        group: tomcat
        mode: u+rwx,g+rx,o=rx
        recurse: yes
      with_items:
        - "{{ tomcat_install_directory }}"
        - "{{ tomcat_install_directory }}/conf"
        - "{{ tomcat_install_directory }}/webapps"
        - "{{ tomcat_install_directory }}/logs"
        - "{{ tomcat_install_directory }}/temp"
        - "{{ tomcat_install_directory }}/bin"

    - name: Creating a service file 
      become: yes
      copy:
        content: |-
          [Unit]
          Description=Tomcat Service 
          Requires=network.target
          After=network.target

          [Service]
          Type=forking 
          User=tomcat
          Environment="CATALINA_PID=/opt/tomcat10/logs/tomcat.pid"
          Environment="CATALINA_BASE=/opt/tomcat10" 
          Environment="CATALINA_HOME=/opt/tomcat10"
          Environment="CATALINA_OPTS=-Xms512M -Xmxl024M -server -XX:+UseParallelGC"
          
          ExecStart=/opt/tomcat10/bin/startup.sh 
          ExecStop=/opt/tomcat10/bin/shutdown.sh 
          Restart=on-abnormal

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/tomcat.service

    - name: Reload the SystemD to re-read configurations
      become: yes
      systemd:
        daemon_reload: yes
    
    - name: Start and Enable Tomcat 10 on server
      become: yes
      systemd:
        name: tomcat
        enabled: yes
        state: started

    - name: Connect to Tomcat server on port 8080 and check status 200 - Try 5 times
      tags: test
      uri:
        url: http://localhost:8080
      register: result
      until: "result.status == 200"
      retries: 5
      delay: 10
