---
- name: Remove Apache Tomcat 10
  hosts: webservers
  remote_user: ec2-user
  become: true

  tasks:
    - name: Stop Tomcat Service
      systemd:
        name: tomcat
        state: stopped
      ignore_errors: yes

    - name: Disable Tomcat Service
      systemd:
        name: tomcat
        enabled: no
        state: stopped
      ignore_errors: yes

    - name: Remove Tomcat Service file
      file:
        path: /etc/systemd/system/tomcat.service
        state: absent
      notify: reload systemd

    - name: Remove Tomcat Installation Directory
      file:
        path: /opt/tomcat10
        state: absent
      ignore_errors: yes

    - name: Remove Tomcat User
      user:
        name: tomcat
        state: absent
      ignore_errors: yes

    - name: Remove Tomcat Group
      group:
        name: tomcat
        state: absent
      ignore_errors: yes

  handlers:
    - name: reload systemd
      systemd:
        daemon_reload: yes
