---
- name: Install Nexus Repository Manager
  hosts: webservers
  become: true
  vars:
    nexus_version: "3.30.0-01"
    nexus_download_url: "https://download.sonatype.com/nexus/3/nexus-{{ nexus_version }}-unix.tar.gz"
    nexus_install_directory: "/opt/nexus"
    nexus_data_directory: "/opt/nexus-data"
    nexus_user: "nexus"
    nexus_group: "nexus"

  tasks:
    - name: Create Nexus User
      user:
        name: "{{ nexus_user }}"
        comment: "Nexus Repository User"
        system: true
        shell: /bin/bash

    - name: Create Nexus Group
      group:
        name: "{{ nexus_group }}"
        system: true

    - name: Create Nexus Directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ nexus_user }}"
        group: "{{ nexus_group }}"
        mode: '0755'
      loop:
        - "{{ nexus_install_directory }}"
        - "{{ nexus_data_directory }}"

    - name: Download Nexus
      get_url:
        url: "{{ nexus_download_url }}"
        dest: "/tmp/nexus.tar.gz"

    - name: Extract Nexus Archive
      unarchive:
        src: "/tmp/nexus.tar.gz"
        dest: "{{ nexus_install_directory }}"
        remote_src: yes
        extra_opts: [--strip-components=1]
        owner: "{{ nexus_user }}"
        group: "{{ nexus_group }}"

    - name: Configure Nexus to Use Custom Data Directory
      lineinfile:
        path: "{{ nexus_install_directory }}/bin/nexus.vmoptions"
        regexp: '^(-Dkaraf.data=).*'
        line: '-Dkaraf.data={{ nexus_data_directory }}'
        state: present

    - name: Create Nexus Service File
      template:
        src: nexus.service.j2
        dest: /etc/systemd/system/nexus.service

    - name: Reload Systemd to Recognize Nexus Service
      systemd:
        daemon_reload: yes

    - name: Enable and Start Nexus Service
      systemd:
        name: nexus
        enabled: yes
        state: started
