---
- name: Remove SonarQube
  hosts: webservers
  become: true
  vars:
    sonarqube_install_directory: "/opt/sonarqube"
    sonarqube_user: "sonarqube"
    sonarqube_group: "sonarqube"

  tasks:
    - name: Stop SonarQube Service
      systemd:
        name: sonarqube
        state: stopped
      ignore_errors: yes

    - name: Disable SonarQube Service
      systemd:
        name: sonarqube
        enabled: no
      ignore_errors: yes

    - name: Remove SonarQube Service File
      file:
        path: /etc/systemd/system/sonarqube.service
        state: absent
      notify: Reload systemd

    - name: Remove SonarQube Installation Directory
      file:
        path: "{{ sonarqube_install_directory }}"
        state: absent
        recurse: yes

    - name: Remove SonarQube User
      user:
        name: "{{ sonarqube_user }}"
        state: absent
      ignore_errors: yes

    - name: Remove SonarQube Group
      group:
        name: "{{ sonarqube_group }}"
        state: absent
      ignore_errors: yes

  handlers:
    - name: Reload systemd
      systemd:
        daemon_reload: yes
